### GET request to example server
POST https://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe",
  "email": "test@example.com",
  "address": "123 Main Street",
  "dateOfBirth": "1995-05-09",
  "registeredDate": "2024-11-28"
}

###